apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: pihole-serivce
    app.kubernetes.io/version: 2.18.0
  name: pihole-service
  namespace: pihole
spec:
  clusterIP: 10.96.0.12
  clusterIPs:
  - 10.96.0.12
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  externalIPs:
    - 192.168.50.3
  selector:
    app.kubernetes.io/name: pihole
